id: P007962
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016972
  title: རྫོགས་པ་ཆེན་པོ་ཀློང་ཆེན་སྙིང་ཐིག་གི་འདོན་ཆ་དཔལ་ཆེན་འདུས་པ་རྩལ་གི་ཕྱག་བཞེས་ལྟར་བསྒྲིགས་པ
  author: ''
  volumes:
    f0e4e382ad9545d99e81ea3eee4e7cb6:
      image_group_id: I01JW184
      title: ''
      volume_number: 1
      total_pages: 898
ebook_metadata:
  title: རྫོགས་པ་ཆེན་པོ་ཀློང་ཆེན་སྙིང་ཐིག་གི་འདོན་ཆ་དཔལ་ཆེན་འདུས་པ་རྩལ་གི་ཕྱག་བཞེས་ལྟར་བསྒྲིགས་པ
  author: ''
  sku: P007962
  cover: cover.jpg
  layers:
  - pagination
