id: opecha:P007962
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016972
  title: རྫོགས་པ་ཆེན་པོ་ཀློང་ཆེན་སྙིང་ཐིག་གི་འདོན་ཆ་དཔལ་ཆེན་འདུས་པ་རྩལ་གི་ཕྱག་བཞེས་ལྟར་བསྒྲིགས་པ
  volume: ''
  author: ''
